title: Ashik Nasim
logo: assets/headshot_circle.jfif
description: >
  Data Scientist skilled in Python and Machine Learning for Data-Driven Solutions
# Uncomment the following line if you want to enable download links
# show_downloads: true
theme: jekyll-theme-minimal
